/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedReengagementRouteImport } from './routes/_authenticated/reengagement'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedGbpRouteImport } from './routes/_authenticated/gbp'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedCompetitiveIntelligenceRouteImport } from './routes/_authenticated/competitive-intelligence'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as ApiPublicMetaAuditRouteImport } from './routes/api/public/meta-audit'
import { Route as ApiMetaWebhookRouteImport } from './routes/api/meta/webhook'
import { Route as AuthenticatedLeadsNewRouteImport } from './routes/_authenticated/leads.new'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedAgentsSlugRouteImport } from './routes/_authenticated/agents.$slug'
import { Route as AuthenticatedAdsMetaRouteImport } from './routes/_authenticated/ads.meta'
import { Route as AuthenticatedAdsGoogleRouteImport } from './routes/_authenticated/ads.google'
import { Route as ApiPublicLeadsCaptureRouteImport } from './routes/api/public/leads/capture'
import { Route as AuthenticatedSettingsIntegrationsGoogleRouteImport } from './routes/_authenticated/settings.integrations.google'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google/oauth/callback'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReengagementRoute =
  AuthenticatedReengagementRouteImport.update({
    id: '/reengagement',
    path: '/reengagement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGbpRoute = AuthenticatedGbpRouteImport.update({
  id: '/gbp',
  path: '/gbp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitiveIntelligenceRoute =
  AuthenticatedCompetitiveIntelligenceRouteImport.update({
    id: '/competitive-intelligence',
    path: '/competitive-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const ApiPublicMetaAuditRoute = ApiPublicMetaAuditRouteImport.update({
  id: '/api/public/meta-audit',
  path: '/api/public/meta-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaWebhookRoute = ApiMetaWebhookRouteImport.update({
  id: '/api/meta/webhook',
  path: '/api/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsNewRoute = AuthenticatedLeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedAgentsSlugRoute = AuthenticatedAgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)
const AuthenticatedAdsMetaRoute = AuthenticatedAdsMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => AuthenticatedAdsRoute,
} as any)
const AuthenticatedAdsGoogleRoute = AuthenticatedAdsGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => AuthenticatedAdsRoute,
} as any)
const ApiPublicLeadsCaptureRoute = ApiPublicLeadsCaptureRouteImport.update({
  id: '/api/public/leads/capture',
  path: '/api/public/leads/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIntegrationsGoogleRoute =
  AuthenticatedSettingsIntegrationsGoogleRouteImport.update({
    id: '/integrations/google',
    path: '/integrations/google',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google/oauth/callback',
    path: '/api/public/google/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/ads': typeof AuthenticatedAdsRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/command': typeof AuthenticatedCommandRoute
  '/competitive-intelligence': typeof AuthenticatedCompetitiveIntelligenceRoute
  '/content': typeof AuthenticatedContentRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gbp': typeof AuthenticatedGbpRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reengagement': typeof AuthenticatedReengagementRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/ads/google': typeof AuthenticatedAdsGoogleRoute
  '/ads/meta': typeof AuthenticatedAdsMetaRoute
  '/agents/$slug': typeof AuthenticatedAgentsSlugRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/new': typeof AuthenticatedLeadsNewRoute
  '/api/meta/webhook': typeof ApiMetaWebhookRoute
  '/api/public/meta-audit': typeof ApiPublicMetaAuditRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/integrations/google': typeof AuthenticatedSettingsIntegrationsGoogleRoute
  '/api/public/leads/capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/ads': typeof AuthenticatedAdsRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/command': typeof AuthenticatedCommandRoute
  '/competitive-intelligence': typeof AuthenticatedCompetitiveIntelligenceRoute
  '/content': typeof AuthenticatedContentRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gbp': typeof AuthenticatedGbpRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reengagement': typeof AuthenticatedReengagementRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/ads/google': typeof AuthenticatedAdsGoogleRoute
  '/ads/meta': typeof AuthenticatedAdsMetaRoute
  '/agents/$slug': typeof AuthenticatedAgentsSlugRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/new': typeof AuthenticatedLeadsNewRoute
  '/api/meta/webhook': typeof ApiMetaWebhookRoute
  '/api/public/meta-audit': typeof ApiPublicMetaAuditRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/integrations/google': typeof AuthenticatedSettingsIntegrationsGoogleRoute
  '/api/public/leads/capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRouteWithChildren
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/competitive-intelligence': typeof AuthenticatedCompetitiveIntelligenceRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gbp': typeof AuthenticatedGbpRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reengagement': typeof AuthenticatedReengagementRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/ads/google': typeof AuthenticatedAdsGoogleRoute
  '/_authenticated/ads/meta': typeof AuthenticatedAdsMetaRoute
  '/_authenticated/agents/$slug': typeof AuthenticatedAgentsSlugRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/leads/new': typeof AuthenticatedLeadsNewRoute
  '/api/meta/webhook': typeof ApiMetaWebhookRoute
  '/api/public/meta-audit': typeof ApiPublicMetaAuditRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/integrations/google': typeof AuthenticatedSettingsIntegrationsGoogleRoute
  '/api/public/leads/capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/ads'
    | '/agents'
    | '/command'
    | '/competitive-intelligence'
    | '/content'
    | '/copilot'
    | '/dashboard'
    | '/gbp'
    | '/intelligence'
    | '/knowledge'
    | '/leads'
    | '/notifications'
    | '/reengagement'
    | '/revenue'
    | '/reviews'
    | '/settings'
    | '/ads/google'
    | '/ads/meta'
    | '/agents/$slug'
    | '/leads/$id'
    | '/leads/new'
    | '/api/meta/webhook'
    | '/api/public/meta-audit'
    | '/leads/'
    | '/settings/'
    | '/settings/integrations/google'
    | '/api/public/leads/capture'
    | '/api/public/google/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/ads'
    | '/agents'
    | '/command'
    | '/competitive-intelligence'
    | '/content'
    | '/copilot'
    | '/dashboard'
    | '/gbp'
    | '/intelligence'
    | '/knowledge'
    | '/notifications'
    | '/reengagement'
    | '/revenue'
    | '/reviews'
    | '/ads/google'
    | '/ads/meta'
    | '/agents/$slug'
    | '/leads/$id'
    | '/leads/new'
    | '/api/meta/webhook'
    | '/api/public/meta-audit'
    | '/leads'
    | '/settings'
    | '/settings/integrations/google'
    | '/api/public/leads/capture'
    | '/api/public/google/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/_authenticated/ads'
    | '/_authenticated/agents'
    | '/_authenticated/command'
    | '/_authenticated/competitive-intelligence'
    | '/_authenticated/content'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/gbp'
    | '/_authenticated/intelligence'
    | '/_authenticated/knowledge'
    | '/_authenticated/leads'
    | '/_authenticated/notifications'
    | '/_authenticated/reengagement'
    | '/_authenticated/revenue'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/ads/google'
    | '/_authenticated/ads/meta'
    | '/_authenticated/agents/$slug'
    | '/_authenticated/leads/$id'
    | '/_authenticated/leads/new'
    | '/api/meta/webhook'
    | '/api/public/meta-audit'
    | '/_authenticated/leads/'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/integrations/google'
    | '/api/public/leads/capture'
    | '/api/public/google/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiMetaWebhookRoute: typeof ApiMetaWebhookRoute
  ApiPublicMetaAuditRoute: typeof ApiPublicMetaAuditRoute
  ApiPublicLeadsCaptureRoute: typeof ApiPublicLeadsCaptureRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reengagement': {
      id: '/_authenticated/reengagement'
      path: '/reengagement'
      fullPath: '/reengagement'
      preLoaderRoute: typeof AuthenticatedReengagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gbp': {
      id: '/_authenticated/gbp'
      path: '/gbp'
      fullPath: '/gbp'
      preLoaderRoute: typeof AuthenticatedGbpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitive-intelligence': {
      id: '/_authenticated/competitive-intelligence'
      path: '/competitive-intelligence'
      fullPath: '/competitive-intelligence'
      preLoaderRoute: typeof AuthenticatedCompetitiveIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/api/public/meta-audit': {
      id: '/api/public/meta-audit'
      path: '/api/public/meta-audit'
      fullPath: '/api/public/meta-audit'
      preLoaderRoute: typeof ApiPublicMetaAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/webhook': {
      id: '/api/meta/webhook'
      path: '/api/meta/webhook'
      fullPath: '/api/meta/webhook'
      preLoaderRoute: typeof ApiMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads/new': {
      id: '/_authenticated/leads/new'
      path: '/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof AuthenticatedLeadsNewRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/agents/$slug': {
      id: '/_authenticated/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AuthenticatedAgentsSlugRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/ads/meta': {
      id: '/_authenticated/ads/meta'
      path: '/meta'
      fullPath: '/ads/meta'
      preLoaderRoute: typeof AuthenticatedAdsMetaRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/_authenticated/ads/google': {
      id: '/_authenticated/ads/google'
      path: '/google'
      fullPath: '/ads/google'
      preLoaderRoute: typeof AuthenticatedAdsGoogleRouteImport
      parentRoute: typeof AuthenticatedAdsRoute
    }
    '/api/public/leads/capture': {
      id: '/api/public/leads/capture'
      path: '/api/public/leads/capture'
      fullPath: '/api/public/leads/capture'
      preLoaderRoute: typeof ApiPublicLeadsCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations/google': {
      id: '/_authenticated/settings/integrations/google'
      path: '/integrations/google'
      fullPath: '/settings/integrations/google'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsGoogleRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/api/public/google/oauth/callback': {
      id: '/api/public/google/oauth/callback'
      path: '/api/public/google/oauth/callback'
      fullPath: '/api/public/google/oauth/callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdsRouteChildren {
  AuthenticatedAdsGoogleRoute: typeof AuthenticatedAdsGoogleRoute
  AuthenticatedAdsMetaRoute: typeof AuthenticatedAdsMetaRoute
}

const AuthenticatedAdsRouteChildren: AuthenticatedAdsRouteChildren = {
  AuthenticatedAdsGoogleRoute: AuthenticatedAdsGoogleRoute,
  AuthenticatedAdsMetaRoute: AuthenticatedAdsMetaRoute,
}

const AuthenticatedAdsRouteWithChildren =
  AuthenticatedAdsRoute._addFileChildren(AuthenticatedAdsRouteChildren)

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsSlugRoute: typeof AuthenticatedAgentsSlugRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsSlugRoute: AuthenticatedAgentsSlugRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsNewRoute: typeof AuthenticatedLeadsNewRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsNewRoute: AuthenticatedLeadsNewRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsIntegrationsGoogleRoute: typeof AuthenticatedSettingsIntegrationsGoogleRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsIntegrationsGoogleRoute:
    AuthenticatedSettingsIntegrationsGoogleRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRouteWithChildren
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedCompetitiveIntelligenceRoute: typeof AuthenticatedCompetitiveIntelligenceRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGbpRoute: typeof AuthenticatedGbpRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReengagementRoute: typeof AuthenticatedReengagementRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdsRoute: AuthenticatedAdsRouteWithChildren,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedCompetitiveIntelligenceRoute:
    AuthenticatedCompetitiveIntelligenceRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGbpRoute: AuthenticatedGbpRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReengagementRoute: AuthenticatedReengagementRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  ApiMetaWebhookRoute: ApiMetaWebhookRoute,
  ApiPublicMetaAuditRoute: ApiPublicMetaAuditRoute,
  ApiPublicLeadsCaptureRoute: ApiPublicLeadsCaptureRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
